FormEvosMovesPointers::
; Entry layout, 4 bytes:
;     db <base species>, <form index>
;     dw <record>
;
; Generated by tools/gen_form_evos_moves.py (Phase 2). Each record below is
; a verbatim copy of its base species' level-up learnset at generation time -
; hand-edit the individual data/pokemon/form_evos_moves/<name>.asm files
; freely; this table itself only needs an edit if a form is added or removed.
	db MEOWTH, 1
	dw AmeowthFormEvosMoves
	db MEOWTH, 2
	dw GmeowthFormEvosMoves
	db DUGTRIO, 1
	dw AdugtrioFormEvosMoves
	db DUGTRIO, 2
	dw WugtrioFormEvosMoves
	db DIGLETT, 1
	dw AdiglettFormEvosMoves
	db DIGLETT, 2
	dw WiglettFormEvosMoves
	db PERSIAN, 1
	dw ApersianFormEvosMoves
	db PERSIAN, 2
	dw PerrserkerFormEvosMoves
	db JOLTEON, 1
	dw EspeonFormEvosMoves
	db JOLTEON, 2
	dw UmbreonFormEvosMoves
	db VAPOREON, 1
	dw GlaceonFormEvosMoves
	db VAPOREON, 2
	dw SylveonFormEvosMoves
	db FLAREON, 1
	dw LeafeonFormEvosMoves
	db TAUROS, 1
	dw PtauroscombatFormEvosMoves
	db TAUROS, 2
	dw PtaurosblazeFormEvosMoves
	db TAUROS, 3
	dw PtaurosaquaFormEvosMoves
	db TENTACOOL, 1
	dw ToedscoolFormEvosMoves
	db TENTACRUEL, 1
	dw ToedscruelFormEvosMoves
	db JIGGLYPUFF, 1
	dw ScreamtailFormEvosMoves
	db MAGNETON, 1
	dw SandyshocksFormEvosMoves
	db EXEGGUTOR, 1
	dw AexeggutorFormEvosMoves
	db GEODUDE, 1
	dw AgeodudeFormEvosMoves
	db GOLEM, 1
	dw AgolemFormEvosMoves
	db GRAVELER, 1
	dw AgravelerFormEvosMoves
	db GRIMER, 1
	dw AgrimerFormEvosMoves
	db MAROWAK, 1
	dw AmarowakFormEvosMoves
	db MUK, 1
	dw AmukFormEvosMoves
	db NINETALES, 1
	dw AninetalesFormEvosMoves
	db RAICHU, 1
	dw AraichuFormEvosMoves
	db RATICATE, 1
	dw AraticateFormEvosMoves
	db RATTATA, 1
	dw ArattataFormEvosMoves
	db SANDSHREW, 1
	dw AsandshrewFormEvosMoves
	db SANDSLASH, 1
	dw AsandslashFormEvosMoves
	db VULPIX, 1
	dw AvulpixFormEvosMoves
	db ARTICUNO, 1
	dw GarticunoFormEvosMoves
	db FARFETCHD, 1
	dw GfarfetchdFormEvosMoves
	db MOLTRES, 1
	dw GmoltresFormEvosMoves
	db MR_MIME, 1
	dw GmrmimeFormEvosMoves
	db PONYTA, 1
	dw GponytaFormEvosMoves
	db RAPIDASH, 1
	dw GrapidashFormEvosMoves
	db SLOWBRO, 1
	dw GslowbroFormEvosMoves
	db SLOWKING, 1
	dw GslowkingFormEvosMoves
	db SLOWPOKE, 1
	dw GslowpokeFormEvosMoves
	db WEEZING, 1
	dw GweezingFormEvosMoves
	db ZAPDOS, 1
	dw GzapdosFormEvosMoves
	db ARCANINE, 1
	dw HarcanineFormEvosMoves
	db ELECTRODE, 1
	dw HelectrodeFormEvosMoves
	db GROWLITHE, 1
	dw HgrowlitheFormEvosMoves
	db QWILFISH, 1
	dw HqwilfishFormEvosMoves
	db SNEASEL, 1
	dw HsneaselFormEvosMoves
	db VOLTORB, 1
	dw HvoltorbFormEvosMoves
	db WOOPER, 1
	dw PwooperFormEvosMoves
	db 0 ; terminator

	INCLUDE "data/pokemon/form_evos_moves/ameowth.asm"
	INCLUDE "data/pokemon/form_evos_moves/gmeowth.asm"
	INCLUDE "data/pokemon/form_evos_moves/adugtrio.asm"
	INCLUDE "data/pokemon/form_evos_moves/wugtrio.asm"
	INCLUDE "data/pokemon/form_evos_moves/adiglett.asm"
	INCLUDE "data/pokemon/form_evos_moves/wiglett.asm"
	INCLUDE "data/pokemon/form_evos_moves/apersian.asm"
	INCLUDE "data/pokemon/form_evos_moves/perrserker.asm"
	INCLUDE "data/pokemon/form_evos_moves/espeon.asm"
	INCLUDE "data/pokemon/form_evos_moves/umbreon.asm"
	INCLUDE "data/pokemon/form_evos_moves/glaceon.asm"
	INCLUDE "data/pokemon/form_evos_moves/sylveon.asm"
	INCLUDE "data/pokemon/form_evos_moves/leafeon.asm"
	INCLUDE "data/pokemon/form_evos_moves/ptauroscombat.asm"
	INCLUDE "data/pokemon/form_evos_moves/ptaurosblaze.asm"
	INCLUDE "data/pokemon/form_evos_moves/ptaurosaqua.asm"
	INCLUDE "data/pokemon/form_evos_moves/toedscool.asm"
	INCLUDE "data/pokemon/form_evos_moves/toedscruel.asm"
	INCLUDE "data/pokemon/form_evos_moves/screamtail.asm"
	INCLUDE "data/pokemon/form_evos_moves/sandyshocks.asm"
	INCLUDE "data/pokemon/form_evos_moves/aexeggutor.asm"
	INCLUDE "data/pokemon/form_evos_moves/ageodude.asm"
	INCLUDE "data/pokemon/form_evos_moves/agolem.asm"
	INCLUDE "data/pokemon/form_evos_moves/agraveler.asm"
	INCLUDE "data/pokemon/form_evos_moves/agrimer.asm"
	INCLUDE "data/pokemon/form_evos_moves/amarowak.asm"
	INCLUDE "data/pokemon/form_evos_moves/amuk.asm"
	INCLUDE "data/pokemon/form_evos_moves/aninetales.asm"
	INCLUDE "data/pokemon/form_evos_moves/araichu.asm"
	INCLUDE "data/pokemon/form_evos_moves/araticate.asm"
	INCLUDE "data/pokemon/form_evos_moves/arattata.asm"
	INCLUDE "data/pokemon/form_evos_moves/asandshrew.asm"
	INCLUDE "data/pokemon/form_evos_moves/asandslash.asm"
	INCLUDE "data/pokemon/form_evos_moves/avulpix.asm"
	INCLUDE "data/pokemon/form_evos_moves/garticuno.asm"
	INCLUDE "data/pokemon/form_evos_moves/gfarfetchd.asm"
	INCLUDE "data/pokemon/form_evos_moves/gmoltres.asm"
	INCLUDE "data/pokemon/form_evos_moves/gmrmime.asm"
	INCLUDE "data/pokemon/form_evos_moves/gponyta.asm"
	INCLUDE "data/pokemon/form_evos_moves/grapidash.asm"
	INCLUDE "data/pokemon/form_evos_moves/gslowbro.asm"
	INCLUDE "data/pokemon/form_evos_moves/gslowking.asm"
	INCLUDE "data/pokemon/form_evos_moves/gslowpoke.asm"
	INCLUDE "data/pokemon/form_evos_moves/gweezing.asm"
	INCLUDE "data/pokemon/form_evos_moves/gzapdos.asm"
	INCLUDE "data/pokemon/form_evos_moves/harcanine.asm"
	INCLUDE "data/pokemon/form_evos_moves/helectrode.asm"
	INCLUDE "data/pokemon/form_evos_moves/hgrowlithe.asm"
	INCLUDE "data/pokemon/form_evos_moves/hqwilfish.asm"
	INCLUDE "data/pokemon/form_evos_moves/hsneasel.asm"
	INCLUDE "data/pokemon/form_evos_moves/hvoltorb.asm"
	INCLUDE "data/pokemon/form_evos_moves/pwooper.asm"
