from __future__ import annotations

from pathlib import Path
import re


CONST_RE = re.compile(r"^const\s+([A-Za-z0-9_]+)(?:\s*,.*)?$")
# constants/event_constants.asm is generated by tools/gen_event_constants.py
# and emits explicit `DEF NAME EQU <expr>` instead of a const_def/const run,
# because its layout is not monotonic (leftover events fill holes inside the
# byte-aligned trainer windows). <expr> may reference an earlier name, e.g.
# `EQU EVENT_GRAVEYARD_BASE + 3`.
DEF_EQU_RE = re.compile(r"^DEF\s+([A-Za-z0-9_]+)\s+EQU\s+(.+)$")
MAP_CONST_RE = re.compile(r"^map_const\s+([A-Za-z0-9_]+)\s*,")
TRAINER_CONST_RE = re.compile(r"^trainer_const\s+([A-Za-z0-9_]+)")


def _integer_expression(expression: str, names=None) -> int:
    converted = re.sub(r"\$([0-9a-fA-F]+)", r"0x\1", expression.strip())
    if names:
        # Resolve identifiers against symbols defined earlier in the file, so
        # generated forms like `EQU EVENT_GRAVEYARD_BASE + 3` parse.
        converted = re.sub(
            r"[A-Za-z_][A-Za-z0-9_]*",
            lambda m: str(names[m.group(0)]) if m.group(0) in names
            else m.group(0),
            converted,
        )
    # rgbds tolerates leading zeros in decimal literals (e.g.
    # `DEF NOT_VERY_EFFECTIVE EQU 05`); Python does not.
    converted = re.sub(r"\b0+(\d)", r"\1", converted)
    if not re.fullmatch(r"[0-9a-fA-FxX()+\-\s]+", converted):
        raise ValueError(f"Unsupported integer expression: {expression!r}")
    return int(eval(converted, {"__builtins__": {}}, {}))


def parse_rgbds_constants(path: Path) -> dict[str, int]:
    """Resolve the const/const_next/const_skip subset used by event_constants.asm."""
    current = 0
    constants: dict[str, int] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if not line:
            continue
        if line.startswith("const_def"):
            expression = line[len("const_def") :].strip()
            current = _integer_expression(expression) if expression else 0
            continue
        if line.startswith("const_next"):
            current = _integer_expression(line[len("const_next") :])
            continue
        if line.startswith("const_skip"):
            expression = line[len("const_skip") :].strip()
            current += _integer_expression(expression) if expression else 1
            continue
        match = CONST_RE.match(line)
        if match:
            constants[match.group(1)] = current
            current += 1
            continue
        match = DEF_EQU_RE.match(line)
        if match:
            try:
                constants[match.group(1)] = _integer_expression(
                    match.group(2), constants)
            except (ValueError, SyntaxError):
                # Not a plain integer DEF (string, macro, forward reference).
                # Skip it rather than failing the whole parse, which is what
                # this function did for every DEF before the generated
                # event_constants.asm needed them.
                pass
    return constants


def parse_map_constants(path: Path) -> dict[str, int]:
    """Resolve map_const declarations in their const_def order."""
    current = 0
    constants: dict[str, int] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if line.startswith("const_def"):
            expression = line[len("const_def") :].strip()
            current = _integer_expression(expression) if expression else 0
            continue
        match = MAP_CONST_RE.match(line)
        if match:
            constants[match.group(1)] = current
            current += 1
    return constants


def parse_trainer_constants(path: Path) -> dict[str, int]:
    """Resolve OPP_* values produced by trainer_const.

    The offset is read from the file's own `DEF OPP_ID_OFFSET EQU n` rather than
    hardcoded. It used to be a literal 200 here, which meant this "derived"
    helper would have silently kept reporting pre-change ids after the offset
    was lowered to 160 in Phase 0a of the gym-leader expansion.
    """
    current = 0
    offset: int | None = None
    constants: dict[str, int] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        def_match = DEF_EQU_RE.match(line)
        if def_match and def_match.group(1) == "OPP_ID_OFFSET":
            offset = _integer_expression(def_match.group(2))
            continue
        if line.startswith("const_def"):
            expression = line[len("const_def") :].strip()
            current = _integer_expression(expression) if expression else 0
            continue
        match = TRAINER_CONST_RE.match(line)
        if match:
            if offset is None:
                raise ValueError(
                    f"{path}: trainer_const seen before DEF OPP_ID_OFFSET"
                )
            constants[match.group(1)] = offset + current
            current += 1
    return constants




def parse_trainer_class_indexes(path: Path) -> dict[str, int]:
    """Resolve the raw class indexes produced by trainer_const.

    This is what wTrainerClass holds - the `const` half of trainer_const, with
    OPP_ID_OFFSET NOT applied. Use this when writing wTrainerClass directly;
    use parse_trainer_constants when comparing against wCurOpponent.

    Added because a test computed the class as `parse_trainer_constants(...)[k]
    - 200`, which silently returned the wrong class the moment OPP_ID_OFFSET
    stopped being 200.
    """
    current = 0
    constants: dict[str, int] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if line.startswith("const_def"):
            expression = line[len("const_def") :].strip()
            current = _integer_expression(expression) if expression else 0
            continue
        match = TRAINER_CONST_RE.match(line)
        if match:
            constants[match.group(1)] = current
            current += 1
    return constants

def parse_object_events(path: Path) -> list[tuple[str, ...]]:
    """Return comma-separated object_event arguments in declaration order."""
    objects: list[tuple[str, ...]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if not line.startswith("object_event "):
            continue
        arguments = line[len("object_event ") :]
        objects.append(tuple(part.strip() for part in arguments.split(",")))
    return objects


def parse_warp_events(path: Path) -> list[tuple[str, ...]]:
    warps: list[tuple[str, ...]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if line.startswith("warp_event "):
            arguments = line[len("warp_event ") :]
            warps.append(tuple(part.strip() for part in arguments.split(",")))
    return warps


def parse_rgbds_integer(expression: str) -> int:
    return _integer_expression(expression)


def parse_db_table(path: Path, label: str) -> list[tuple[str, ...]]:
    """Parse a simple label followed by db rows through its db -1 sentinel."""
    rows: list[tuple[str, ...]] = []
    in_table = False
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if not in_table:
            in_table = line == f"{label}:"
            continue
        if not line:
            continue
        if not line.startswith("db "):
            continue
        values = tuple(part.strip() for part in line[3:].split(","))
        if values[0] in {"-1", "$ff"}:
            break
        rows.append(values)
    return rows
