import importlib.util
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location(
    "check_facility_premades", ROOT / "tools" / "check_facility_premades.py"
)
assert SPEC and SPEC.loader
validator = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(validator)


GEN_SPEC = importlib.util.spec_from_file_location(
    "gen_facility_room_table", ROOT / "tools" / "gen_facility_room_table.py"
)
assert GEN_SPEC and GEN_SPEC.loader
generator = importlib.util.module_from_spec(GEN_SPEC)
GEN_SPEC.loader.exec_module(generator)

GENERATOR_MARK = "; generated by tools/gen_facility_room_table.py"


class FacilityDescriptorTableFreshnessTest(unittest.TestCase):
    """The descriptor table in the generator source must equal what the
    validator currently measures.

    Socket masks, PFAC_TPL_ITEM and (since C2) the PFAC_TPL_EXIT_* bits are all
    MEASURED from the payload art, never authored. So editing a .blk without
    regenerating leaves the table describing art that no longer exists, and
    nothing else in the build would notice: the ROM links, every ASSERT holds,
    and the only symptom is a wrong room at runtime. For the exit bits that is a
    safety property - a stale bit can let the boss room stamp a payload that
    strands the boss and both exit warp tiles.
    """

    def test_committed_table_matches_the_validator(self) -> None:
        audit = ROOT / "tools" / "pyboy_smoke" / "artifacts" / "facility_fullroom_audit.txt"
        results = validator.scan_fullrooms()
        self.assertEqual(
            audit.read_text(encoding="utf-8").strip(),
            validator.format_report(results).strip(),
            "facility_fullroom_audit.txt is stale; re-run "
            "tools/check_facility_premades.py --report > that file",
        )

        source = (
            ROOT / "custom_functions" / "procedural_facility_gen.asm"
        ).read_text(encoding="utf-8")
        start = source.index("PFacRoomDescriptors:")
        end = source.index(GENERATOR_MARK)
        self.assertEqual(
            source[start:end].strip(),
            generator.build_table().strip(),
            "the descriptor table is stale; re-run "
            "tools/gen_facility_room_table.py and splice its output in",
        )


class FacilityPremadeContractTest(unittest.TestCase):
    def test_fixture_descriptor_contract(self) -> None:
        self.assertEqual(validator.validate(), [])

    def test_every_template_declares_its_exit_safety(self) -> None:
        """C2. Exit-safe sides are a subset of nothing in particular, but an
        OK template with no exit-safe side at all would silently never be
        eligible for the boss room, which is worth knowing about rather than
        discovering as a coverage hole."""
        unusable = [
            r.filename
            for r in validator.scan_fullrooms()
            if r.status == "OK" and not r.exit_safe
        ]
        self.assertEqual(unusable, [], "template is usable by no exit edge")

    def test_selection_and_generic_fallback(self) -> None:
        for required in range(16):
            for room_id in range(1, 11):
                self.assertTrue(validator.select_fixture(room_id, 1, 1, required))
        self.assertFalse(validator.select_fixture(0, 1, 1, 1))
        self.assertFalse(validator.select_fixture(11, 1, 1, 1))
        self.assertFalse(validator.select_fixture(1, 2, 1, 1))
        self.assertFalse(validator.select_fixture(5, 1, 2, 1))
        self.assertFalse(
            validator.select_fixture(5, 1, 1, 1, corners_clear=False)
        )

    def test_large_decor_fixtures_have_safe_placement(self) -> None:
        for filename, (width, height) in validator.LARGE_DECOR_FIXTURES.items():
            payload = (ROOT / "maps" / filename).read_bytes()
            placements = [
                (room_width, room_height, x, y)
                for room_height in range(height, 8)
                for room_width in range(width, 8)
                for x, y in validator.valid_large_decor_offsets(
                    payload, width, height, room_width, room_height
                )
            ]
            self.assertTrue(placements, filename)

    def test_large_decor_protects_center_cross(self) -> None:
        payload = bytes((0x0E, 0x31, 0x45, 0x2C))
        self.assertFalse(
            validator.large_decor_offset_safe(payload, 2, 2, 2, 2, 0, 0)
        )
        self.assertTrue(
            validator.large_decor_offset_safe(payload, 2, 2, 4, 4, 0, 0)
        )

    def test_actual_door_mask_allows_compact_direction_safe_decor(self) -> None:
        payload = (
            ROOT / "maps" / "ProceduralFacility_2x2_blocktree_decor.blk"
        ).read_bytes()
        self.assertTrue(
            validator.valid_large_decor_offsets(payload, 2, 2, 2, 4, 0x02)
        )

    def test_nested_block_fixture_is_disabled_pending_redesign(self) -> None:
        self.assertNotIn(
            "ProceduralFacility_3x3_block_decor.blk",
            validator.LARGE_DECOR_RUNTIME_FIXTURES,
        )

    def test_disconnect_reproducer_is_disabled_pending_safe_placement(self) -> None:
        self.assertNotIn(
            "ProceduralFacility_2x2_blocktree_decor.blk",
            validator.LARGE_DECOR_RUNTIME_FIXTURES,
        )

    def test_table_is_item_anchor_but_not_walkable_decor(self) -> None:
        self.assertIn(0x47, validator.ITEM_ANCHOR_BLOCKS)
        self.assertNotIn(0x47, validator.FULLY_WALKABLE_DECOR_BLOCKS)
        self.assertTrue(validator.item_anchor_safe([[0x47, 0x0E]], 0, 0))
        self.assertFalse(validator.item_anchor_safe([[0x47, 0x31]], 0, 0))


if __name__ == "__main__":
    unittest.main()
