"""Machine-state checks for retired field moves and unused Yellow trainers."""
from source_constants import parse_rgbds_constants, parse_trainer_class_indexes
from test_smoke import HarnessTestCase, REPO_ROOT


class LaundryScopeSmokeTest(HarnessTestCase):
    def test_hms_have_no_field_menu_or_key_item_restriction(self):
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        moves = parse_rgbds_constants(REPO_ROOT / "constants/move_constants.asm")
        # Machine IDs are generated by add_hm/add_tm, outside the const parser.
        for i, move in enumerate(("CUT", "SURF", "STRENGTH", "FLASH")):
            h.write8("wPartyMon1Moves", moves[move], offset=i)
        h.write8("hWhichPokemon", 0)
        h.write8("wNumFieldMoves", 4)
        h.call_routine("DisplayFieldMoveMonMenu", limit=600)
        self.assertEqual(h.read8("wNumFieldMoves"), 0)
        self.assertEqual(h.read_bytes("wFieldMoves", 4), [0] * 4)
        for item, item_id in (("HM01", 0xC4), ("HM05", 0xC8), ("TM01", 0xC9)):
            with self.subTest(item=item):
                h.write8("wCurItem", item_id)
                h.write8("wIsKeyItem", 1)
                h.call_routine("IsKeyItem_", limit=600)
                self.assertEqual(h.read8("wIsKeyItem"), 0)

    def test_jessie_james_fixed_team_definitions_load(self):
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        species = parse_rgbds_constants(REPO_ROOT / "constants/pokemon_constants.asm")
        classes = parse_trainer_class_indexes(
            REPO_ROOT / "constants/trainer_constants.asm"
        )
        teams = (
            ("EKANS", "MEOWTH", "KOFFING"),
            ("KOFFING", "MEOWTH", "EKANS"),
            ("MEOWTH", "ARBOK", "WEEZING"),
            ("WEEZING", "ARBOK", "MEOWTH"),
        )
        for number, team in enumerate(teams, 1):
            with self.subTest(team=number):
                h.write8("wTrainerClass", classes["JESSIE_JAMES"])
                h.write8("wTrainerNo", number)
                h.call_routine("ReadTrainer", limit=600)
                self.assertEqual(h.read8("wEnemyPartyCount"), 3)
                self.assertEqual(h.read_bytes("wEnemyPartySpecies", 4),
                                 [species[name] for name in team] + [0xFF])

    def test_new_leader_classes_build_their_placeholder_parties(self) -> None:
        """Every new gym-leader class resolves through ReadTrainer end to end.

        This is the check that the eleven new rows landed in the SAME position
        in all six NUM_TRAINERS-keyed tables. `assert_table_length` only proves
        each table has 61 rows; it cannot see a row inserted at the wrong index,
        which is this repo's documented "misaligned table whose count assert
        passes" failure mode. Driving ReadTrainer per class and matching the
        exact species list does see it: a shifted party pointer yields another
        class's team, and a shifted pic/name row yields the wrong bank or name.

        The parties are Phase 1 placeholders (one team each). When Phase 3
        replaces them with the real 8-tier pools, update the expectations here
        rather than deleting the test - the alignment property is permanent.
        """
        assert self.harness is not None
        self.harness.boot_fight2(seed=1)
        species = parse_rgbds_constants(REPO_ROOT / "constants/pokemon_constants.asm")
        classes = parse_trainer_class_indexes(
            REPO_ROOT / "constants" / "trainer_constants.asm"
        )

        expected = {
            "FALKNER": ["PIDGEOTTO", "HOOTHOOT", "NOCTOWL"],
            "BUGSY": ["SPINARAK", "ARIADOS", "SCYTHER"],
            "WHITNEY": ["CLEFAIRY", "MILTANK", "MILTANK"],
            "MORTY": ["GASTLY", "HAUNTER", "MISDREAVUS", "GENGAR"],
            "CHUCK": ["PRIMEAPE", "MACHOKE", "POLIWRATH"],
            "JASMINE": ["MAGNEMITE", "MAGNETON", "ONIX", "STEELIX"],
            "PRYCE": ["SEEL", "SWINUB", "DEWGONG", "PILOSWINE"],
            "CLAIR": ["DRATINI", "HORSEA", "DRAGONAIR", "KINGDRA"],
            "JANINE": ["KOFFING", "VENOMOTH", "ARBOK", "WEEZING"],
            "WILL": ["NATU", "XATU", "JYNX", "EXEGGUTOR", "SLOWBRO"],
            "KAREN": ["MURKROW", "GENGAR", "VENOMOTH", "HOUNDOOM"],
        }

        for name, team in expected.items():
            with self.subTest(leader=name):
                self.harness.write8("wTrainerClass", classes[name])
                self.harness.write8("wTrainerNo", 1)
                self.harness.call_routine("ReadTrainer", limit=600)
                self.assertEqual(self.harness.read8("wEnemyPartyCount"), len(team))
                self.assertEqual(
                    self.harness.read_bytes("wEnemyPartySpecies", len(team) + 1),
                    [species[s] for s in team] + [0xFF],
                )


    def test_trainer_pic_bank_is_data_driven_per_class(self) -> None:
        """GetTrainerInformation publishes each class's pic pointer AND bank.

        Phase 1b replaced _LoadTrainerPic's `cp JESSIE_JAMES` with a bank byte
        in TrainerPicAndMoneyPointers, so a trainer pic may now live in any
        bank. Verified against the built symbol table rather than literals, and
        deliberately spanning three different banks:

          BROCK   -> "Trainer Pics"    (the original bank)
          FALKNER -> "Trainer Pics 2"  (bank $3C, only reachable via the new byte)
          KAREN   -> "Trainer Pics 2"
          JESSIE_JAMES -> its own bank ($2C), the case the old special case existed for

        A wrong stride in the 6-byte row shows up here as a pointer/bank pair
        borrowed from a neighbouring class, which the old 5-byte layout could
        not have detected at all.
        """
        assert self.harness is not None
        self.harness.boot_fight2(seed=1)
        classes = parse_trainer_class_indexes(
            REPO_ROOT / "constants" / "trainer_constants.asm"
        )

        for class_name, pic_label in (
            ("BROCK", "BrockPic"),
            ("FALKNER", "FalknerPic"),
            ("KAREN", "KarenPic"),
            ("JESSIE_JAMES", "JessieJamesPic"),
        ):
            with self.subTest(trainer=class_name):
                want_bank, want_addr = self.harness.symbols.get(pic_label)
                self.harness.write8("wTrainerClass", classes[class_name])
                self.harness.call_routine("GetTrainerInformation", limit=600)
                lo, hi = self.harness.read_bytes("wTrainerPicPointer", 2)
                self.assertEqual(lo | (hi << 8), want_addr)
                self.assertEqual(self.harness.read8("wTrainerPicBank"), want_bank)

    def test_move_swap_restores_audio_state_before_resuming_music(self):
        import io
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        baseline = io.BytesIO()
        h.save_state(baseline)
        bank, wait_address = h.symbols.get("PlayMoveSwapSound.waitSfx")
        # The helper's final EI/RET precedes its local wait routine. Capture
        # before EI, so ordinary subsequent VBlanks cannot alter the evidence.
        seam = wait_address - 2
        rom = h.rom_path.read_bytes()
        offset = bank * 0x4000 + seam - 0x4000
        self.assertEqual(rom[offset:offset + 2], bytes((0xFB, 0xC9)))
        fields = ("wAudioROMBank", "wAudioSavedROMBank",
                  "wMuteAudioAndPauseMusic", "wAudioFadeOutControl")
        # boot_fight2 may stop inside VBlank with IME cleared. Enter through
        # a test-only EI trampoline, matching the normal text caller context.
        # This overrides emulator ROM only; no on-disk ROM bytes are changed.
        target_bank, target = h.symbols.get("PlayMoveSwapSound")
        switch = h.address("Bankswitch")
        entry = 0x3FF0
        trampoline = (0xFB, 0x06, target_bank, 0x21, target & 255,
                      target >> 8, 0xC3, switch & 255, switch >> 8)
        for index, byte in enumerate(trampoline):
            h.pyboy.memory[0, entry + index] = byte
        h.symbols._symbols["AudioTestEntry"] = (0, entry)
        for alarm in (0, 0x80):
            with self.subTest(alarm=alarm):
                h.load_state(baseline)
                h.write8("wLowHealthAlarm", alarm)
                h.write8("wMuteAudioAndPauseMusic", 0)
                h.write8("wAudioFadeOutControl", 0)
                for channel in range(4, 8):
                    h.write8("wChannelSoundIDs", 0, offset=channel)
                expected = {name: h.read8(name) for name in fields}
                captured = {}
                def at_return(_):
                    captured.update({name: h.read8(name) for name in fields})
                    captured["alarm"] = h.read8("wLowHealthAlarm")
                    captured["channels"] = h.read_bytes("wChannelSoundIDs", 4, offset=4)
                h.pyboy.hook_register(bank, seam, at_return, None)
                try:
                    h.call_routine("AudioTestEntry", limit=600)
                finally:
                    h.pyboy.hook_deregister(bank, seam)
                for name, value in expected.items():
                    self.assertEqual(captured[name], value, name)
                self.assertEqual(captured["alarm"], alarm)
                self.assertEqual(captured["channels"], [0] * 4)
