"""Machine-state checks for retired field moves and unused Yellow trainers."""
from source_constants import parse_rgbds_constants, parse_trainer_constants
from test_smoke import HarnessTestCase, REPO_ROOT


class LaundryScopeSmokeTest(HarnessTestCase):
    def test_hms_have_no_field_menu_or_key_item_restriction(self):
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        moves = parse_rgbds_constants(REPO_ROOT / "constants/move_constants.asm")
        # Machine IDs are generated by add_hm/add_tm, outside the const parser.
        for i, move in enumerate(("CUT", "SURF", "STRENGTH", "FLASH")):
            h.write8("wPartyMon1Moves", moves[move], offset=i)
        h.write8("hWhichPokemon", 0)
        h.write8("wNumFieldMoves", 4)
        h.call_routine("DisplayFieldMoveMonMenu", limit=600)
        self.assertEqual(h.read8("wNumFieldMoves"), 0)
        self.assertEqual(h.read_bytes("wFieldMoves", 4), [0] * 4)
        for item, item_id in (("HM01", 0xC4), ("HM05", 0xC8), ("TM01", 0xC9)):
            with self.subTest(item=item):
                h.write8("wCurItem", item_id)
                h.write8("wIsKeyItem", 1)
                h.call_routine("IsKeyItem_", limit=600)
                self.assertEqual(h.read8("wIsKeyItem"), 0)

    def test_jessie_james_fixed_team_definitions_load(self):
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        species = parse_rgbds_constants(REPO_ROOT / "constants/pokemon_constants.asm")
        trainers = parse_trainer_constants(REPO_ROOT / "constants/trainer_constants.asm")
        teams = (
            ("EKANS", "MEOWTH", "KOFFING"),
            ("KOFFING", "MEOWTH", "EKANS"),
            ("MEOWTH", "ARBOK", "WEEZING"),
            ("WEEZING", "ARBOK", "MEOWTH"),
        )
        for number, team in enumerate(teams, 1):
            with self.subTest(team=number):
                h.write8("wTrainerClass", trainers["JESSIE_JAMES"] - 200)
                h.write8("wTrainerNo", number)
                h.call_routine("ReadTrainer", limit=600)
                self.assertEqual(h.read8("wEnemyPartyCount"), 3)
                self.assertEqual(h.read_bytes("wEnemyPartySpecies", 4),
                                 [species[name] for name in team] + [0xFF])
    def test_move_swap_restores_audio_state_before_resuming_music(self):
        import io
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        baseline = io.BytesIO()
        h.save_state(baseline)
        bank, wait_address = h.symbols.get("PlayMoveSwapSound.waitSfx")
        # The helper's final EI/RET precedes its local wait routine. Capture
        # before EI, so ordinary subsequent VBlanks cannot alter the evidence.
        seam = wait_address - 2
        rom = h.rom_path.read_bytes()
        offset = bank * 0x4000 + seam - 0x4000
        self.assertEqual(rom[offset:offset + 2], bytes((0xFB, 0xC9)))
        fields = ("wAudioROMBank", "wAudioSavedROMBank",
                  "wMuteAudioAndPauseMusic", "wAudioFadeOutControl")
        # boot_fight2 may stop inside VBlank with IME cleared. Enter through
        # a test-only EI trampoline, matching the normal text caller context.
        # This overrides emulator ROM only; no on-disk ROM bytes are changed.
        target_bank, target = h.symbols.get("PlayMoveSwapSound")
        switch = h.address("Bankswitch")
        entry = 0x3FF0
        trampoline = (0xFB, 0x06, target_bank, 0x21, target & 255,
                      target >> 8, 0xC3, switch & 255, switch >> 8)
        for index, byte in enumerate(trampoline):
            h.pyboy.memory[0, entry + index] = byte
        h.symbols._symbols["AudioTestEntry"] = (0, entry)
        for alarm in (0, 0x80):
            with self.subTest(alarm=alarm):
                h.load_state(baseline)
                h.write8("wLowHealthAlarm", alarm)
                h.write8("wMuteAudioAndPauseMusic", 0)
                h.write8("wAudioFadeOutControl", 0)
                for channel in range(4, 8):
                    h.write8("wChannelSoundIDs", 0, offset=channel)
                expected = {name: h.read8(name) for name in fields}
                captured = {}
                def at_return(_):
                    captured.update({name: h.read8(name) for name in fields})
                    captured["alarm"] = h.read8("wLowHealthAlarm")
                    captured["channels"] = h.read_bytes("wChannelSoundIDs", 4, offset=4)
                h.pyboy.hook_register(bank, seam, at_return, None)
                try:
                    h.call_routine("AudioTestEntry", limit=600)
                finally:
                    h.pyboy.hook_deregister(bank, seam)
                for name, value in expected.items():
                    self.assertEqual(captured[name], value, name)
                self.assertEqual(captured["alarm"], alarm)
                self.assertEqual(captured["channels"], [0] * 4)