"""Machine-state checks for retired field moves and unused Yellow trainers."""
from source_constants import parse_rgbds_constants, parse_trainer_constants
from test_smoke import HarnessTestCase, REPO_ROOT


class LaundryScopeSmokeTest(HarnessTestCase):
    def test_hms_have_no_field_menu_or_key_item_restriction(self):
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        moves = parse_rgbds_constants(REPO_ROOT / "constants/move_constants.asm")
        # Machine IDs are generated by add_hm/add_tm, outside the const parser.
        for i, move in enumerate(("CUT", "SURF", "STRENGTH", "FLASH")):
            h.write8("wPartyMon1Moves", moves[move], offset=i)
        h.write8("hWhichPokemon", 0)
        h.write8("wNumFieldMoves", 4)
        h.call_routine("DisplayFieldMoveMonMenu", limit=600)
        self.assertEqual(h.read8("wNumFieldMoves"), 0)
        self.assertEqual(h.read_bytes("wFieldMoves", 4), [0] * 4)
        for item, item_id in (("HM01", 0xC4), ("HM05", 0xC8), ("TM01", 0xC9)):
            with self.subTest(item=item):
                h.write8("wCurItem", item_id)
                h.write8("wIsKeyItem", 1)
                h.call_routine("IsKeyItem_", limit=600)
                self.assertEqual(h.read8("wIsKeyItem"), 0)

    def test_jessie_james_fixed_team_definitions_load(self):
        h = self.harness
        assert h is not None
        h.boot_fight2(seed=1)
        species = parse_rgbds_constants(REPO_ROOT / "constants/pokemon_constants.asm")
        trainers = parse_trainer_constants(REPO_ROOT / "constants/trainer_constants.asm")
        teams = (
            ("EKANS", "MEOWTH", "KOFFING"),
            ("KOFFING", "MEOWTH", "EKANS"),
            ("MEOWTH", "ARBOK", "WEEZING"),
            ("WEEZING", "ARBOK", "MEOWTH"),
        )
        for number, team in enumerate(teams, 1):
            with self.subTest(team=number):
                h.write8("wTrainerClass", trainers["JESSIE_JAMES"] - 200)
                h.write8("wTrainerNo", number)
                h.call_routine("ReadTrainer", limit=600)
                self.assertEqual(h.read8("wEnemyPartyCount"), 3)
                self.assertEqual(h.read_bytes("wEnemyPartySpecies", 4),
                                 [species[name] for name in team] + [0xFF])