; Per-move power grading for the party spec system's randomizers (Phase 2).
;
; Generated by tools/reorder_move_ranks.py from
;   Red Rogue Files/red_rogue_comprehensive_package_v3_1_2026-09-08_FIXED/
;     00_CURRENT/red_rogue_gen1_move_rankings_v3_1_runtime_CORRECTED.asm
; NOT wired into `make` - re-run by hand and commit the output, the same
; tools/gen_event_constants.py arrangement. Do not hand-edit MoveRankByID or
; MoveFlagsByID below; MoveRankWeightTable and TMMovesForPartyGen are NOT
; generated and are safe to hand-edit (Phase 5 tuning).
;
; Two fixes applied during generation, both load-bearing (see the script's
; own header for the full explanation):
;   1. The source's 167 rows are sorted by rank descending, not by move id
;      despite its header's claim; re-emitted here in id order.
;   2. The source's MOVEFLAG_* bit assignments do NOT match this tree's
;      constants/party_spec_constants.asm (same 15 names, different bit
;      positions - only MOVEFLAG_BUGGED coincides). Every mask below has been
;      translated bit-by-bit through the flag NAME, not copied as a raw value.
;   PSYCHIC -> PSYCHIC_M, and the ROAR row (repurposed as SUPER_TRANSFORM in
;   this tree) is dropped, per constants/move_constants.asm:54.

; Moves excluded from EVERY randomizer pool, permanently. MOVE_RANK_OFFLIST
; is skipped before it is ever weighted, so none of these six can be selected
; regardless of what a future corpus revision grades them - see FORCED_OFFLIST
; in the generator script.

MoveRankByID::
	table_width 1, MoveRankByID
	db MOVE_RANK_OFFLIST ; NO_MOVE
	db MOVE_RANK_F ; POUND
	db MOVE_RANK_D ; KARATE_CHOP
	db MOVE_RANK_F ; DOUBLESLAP
	db MOVE_RANK_D ; COMET_PUNCH
	db MOVE_RANK_D ; MEGA_PUNCH
	db MOVE_RANK_F ; PAY_DAY
	db MOVE_RANK_B ; FIRE_PUNCH
	db MOVE_RANK_B ; ICE_PUNCH
	db MOVE_RANK_B ; THUNDERPUNCH
	db MOVE_RANK_F ; SCRATCH
	db MOVE_RANK_F ; VICEGRIP
	db MOVE_RANK_C ; GUILLOTINE
	db MOVE_RANK_F ; RAZOR_WIND
	db MOVE_RANK_A ; SWORDS_DANCE
	db MOVE_RANK_F ; CUT
	db MOVE_RANK_D ; GUST
	db MOVE_RANK_D ; WING_ATTACK
	db MOVE_RANK_OFFLIST ; WHIRLWIND
	db MOVE_RANK_D ; FLY
	db MOVE_RANK_B ; BIND
	db MOVE_RANK_D ; SLAM
	db MOVE_RANK_D ; VINE_WHIP
	db MOVE_RANK_B ; STOMP
	db MOVE_RANK_D ; DOUBLE_KICK
	db MOVE_RANK_C ; MEGA_KICK
	db MOVE_RANK_D ; JUMP_KICK
	db MOVE_RANK_D ; ROLLING_KICK
	db MOVE_RANK_F ; SAND_ATTACK
	db MOVE_RANK_B ; HEADBUTT
	db MOVE_RANK_D ; HORN_ATTACK
	db MOVE_RANK_D ; FURY_ATTACK
	db MOVE_RANK_C ; HORN_DRILL
	db MOVE_RANK_F ; TACKLE
	db MOVE_RANK_S ; BODY_SLAM
	db MOVE_RANK_A ; WRAP
	db MOVE_RANK_B ; TAKE_DOWN
	db MOVE_RANK_C ; THRASH
	db MOVE_RANK_B ; DOUBLE_EDGE
	db MOVE_RANK_F ; TAIL_WHIP
	db MOVE_RANK_F ; POISON_STING
	db MOVE_RANK_D ; TWINEEDLE
	db MOVE_RANK_D ; PIN_MISSILE
	db MOVE_RANK_F ; LEER
	db MOVE_RANK_D ; BITE
	db MOVE_RANK_F ; GROWL
	db MOVE_RANK_OFFLIST ; SUPER_TRANSFORM
	db MOVE_RANK_C ; SING
	db MOVE_RANK_F ; SUPERSONIC
	db MOVE_RANK_D ; SONICBOOM
	db MOVE_RANK_F ; DISABLE
	db MOVE_RANK_D ; ACID
	db MOVE_RANK_D ; EMBER
	db MOVE_RANK_B ; FLAMETHROWER
	db MOVE_RANK_F ; MIST
	db MOVE_RANK_D ; WATER_GUN
	db MOVE_RANK_B ; HYDRO_PUMP
	db MOVE_RANK_A ; SURF
	db MOVE_RANK_A ; ICE_BEAM
	db MOVE_RANK_S ; BLIZZARD
	db MOVE_RANK_B ; PSYBEAM
	db MOVE_RANK_B ; BUBBLEBEAM
	db MOVE_RANK_D ; AURORA_BEAM
	db MOVE_RANK_S ; HYPER_BEAM
	db MOVE_RANK_D ; PECK
	db MOVE_RANK_A ; DRILL_PECK
	db MOVE_RANK_D ; SUBMISSION
	db MOVE_RANK_D ; LOW_KICK
	db MOVE_RANK_B ; COUNTER
	db MOVE_RANK_B ; SEISMIC_TOSS
	db MOVE_RANK_B ; STRENGTH
	db MOVE_RANK_D ; ABSORB
	db MOVE_RANK_B ; MEGA_DRAIN
	db MOVE_RANK_C ; LEECH_SEED
	db MOVE_RANK_D ; GROWTH
	db MOVE_RANK_A ; RAZOR_LEAF
	db MOVE_RANK_C ; SOLARBEAM
	db MOVE_RANK_D ; POISONPOWDER
	db MOVE_RANK_A ; STUN_SPORE
	db MOVE_RANK_S ; SLEEP_POWDER
	db MOVE_RANK_C ; PETAL_DANCE
	db MOVE_RANK_F ; STRING_SHOT
	db MOVE_RANK_B ; DRAGON_RAGE
	db MOVE_RANK_B ; FIRE_SPIN
	db MOVE_RANK_D ; THUNDERSHOCK
	db MOVE_RANK_S ; THUNDERBOLT
	db MOVE_RANK_S ; THUNDER_WAVE
	db MOVE_RANK_B ; THUNDER
	db MOVE_RANK_D ; ROCK_THROW
	db MOVE_RANK_S ; EARTHQUAKE
	db MOVE_RANK_C ; FISSURE
	db MOVE_RANK_B ; DIG
	db MOVE_RANK_B ; TOXIC
	db MOVE_RANK_D ; CONFUSION
	db MOVE_RANK_S ; PSYCHIC_M
	db MOVE_RANK_A ; HYPNOSIS
	db MOVE_RANK_D ; MEDITATE
	db MOVE_RANK_B ; AGILITY
	db MOVE_RANK_B ; QUICK_ATTACK
	db MOVE_RANK_D ; RAGE
	db MOVE_RANK_OFFLIST ; TELEPORT
	db MOVE_RANK_B ; NIGHT_SHADE
	db MOVE_RANK_C ; MIMIC
	db MOVE_RANK_D ; SCREECH
	db MOVE_RANK_C ; DOUBLE_TEAM
	db MOVE_RANK_S ; RECOVER
	db MOVE_RANK_F ; HARDEN
	db MOVE_RANK_D ; MINIMIZE
	db MOVE_RANK_F ; SMOKESCREEN
	db MOVE_RANK_B ; CONFUSE_RAY
	db MOVE_RANK_F ; WITHDRAW
	db MOVE_RANK_F ; DEFENSE_CURL
	db MOVE_RANK_D ; BARRIER
	db MOVE_RANK_B ; LIGHT_SCREEN
	db MOVE_RANK_D ; HAZE
	db MOVE_RANK_A ; REFLECT
	db MOVE_RANK_C ; FOCUS_ENERGY
	db MOVE_RANK_F ; BIDE
	db MOVE_RANK_D ; METRONOME
	db MOVE_RANK_D ; MIRROR_MOVE
	db MOVE_RANK_A ; SELFDESTRUCT
	db MOVE_RANK_D ; EGG_BOMB
	db MOVE_RANK_D ; LICK
	db MOVE_RANK_D ; SMOG
	db MOVE_RANK_D ; SLUDGE
	db MOVE_RANK_D ; BONE_CLUB
	db MOVE_RANK_A ; FIRE_BLAST
	db MOVE_RANK_B ; WATERFALL
	db MOVE_RANK_A ; CLAMP
	db MOVE_RANK_B ; SWIFT
	db MOVE_RANK_D ; SKULL_BASH
	db MOVE_RANK_D ; SPIKE_CANNON
	db MOVE_RANK_F ; CONSTRICT
	db MOVE_RANK_A ; AMNESIA
	db MOVE_RANK_F ; KINESIS
	db MOVE_RANK_S ; SOFTBOILED
	db MOVE_RANK_B ; HI_JUMP_KICK
	db MOVE_RANK_B ; GLARE
	db MOVE_RANK_D ; DREAM_EATER
	db MOVE_RANK_D ; POISON_GAS
	db MOVE_RANK_D ; BARRAGE
	db MOVE_RANK_D ; LEECH_LIFE
	db MOVE_RANK_A ; LOVELY_KISS
	db MOVE_RANK_C ; SKY_ATTACK
	db MOVE_RANK_D ; TRANSFORM
	db MOVE_RANK_F ; BUBBLE
	db MOVE_RANK_D ; DIZZY_PUNCH
	db MOVE_RANK_S ; SPORE
	db MOVE_RANK_F ; FLASH
	db MOVE_RANK_F ; PSYWAVE
	db MOVE_RANK_OFFLIST ; SPLASH
	db MOVE_RANK_D ; ACID_ARMOR
	db MOVE_RANK_B ; CRABHAMMER
	db MOVE_RANK_S ; EXPLOSION
	db MOVE_RANK_D ; FURY_SWIPES
	db MOVE_RANK_B ; BONEMERANG
	db MOVE_RANK_C ; REST
	db MOVE_RANK_A ; ROCK_SLIDE
	db MOVE_RANK_B ; HYPER_FANG
	db MOVE_RANK_D ; SHARPEN
	db MOVE_RANK_D ; CONVERSION
	db MOVE_RANK_B ; TRI_ATTACK
	db MOVE_RANK_B ; SUPER_FANG
	db MOVE_RANK_A ; SLASH
	db MOVE_RANK_B ; SUBSTITUTE
	db MOVE_RANK_OFFLIST ; STRUGGLE
	assert_table_length NUM_ATTACKS + 1

; Per-move MOVEFLAG_* mask (constants/party_spec_constants.asm), 2 bytes per
; move id, little-endian - INPUT e = move id, OUTPUT de = mask is
; PartyGenMoveFlags's contract (engine/battle/rogue_build_party.asm); every
; caller already treats it that way.
MoveFlagsByID::
	table_width 2, MoveFlagsByID
	dw $4000 ; NO_MOVE
	dw $0000 ; POUND
	dw $0010 ; KARATE_CHOP
	dw $0000 ; DOUBLESLAP
	dw $0000 ; COMET_PUNCH
	dw $0000 ; MEGA_PUNCH
	dw $0000 ; PAY_DAY
	dw $0000 ; FIRE_PUNCH
	dw $0000 ; ICE_PUNCH
	dw $0000 ; THUNDERPUNCH
	dw $0000 ; SCRATCH
	dw $0000 ; VICEGRIP
	dw $0140 ; GUILLOTINE
	dw $0000 ; RAZOR_WIND
	dw $0102 ; SWORDS_DANCE
	dw $0000 ; CUT
	dw $0000 ; GUST
	dw $0000 ; WING_ATTACK
	dw $0000 ; WHIRLWIND
	dw $0000 ; FLY
	dw $0180 ; BIND
	dw $0000 ; SLAM
	dw $0000 ; VINE_WHIP
	dw $0000 ; STOMP
	dw $0000 ; DOUBLE_KICK
	dw $0000 ; MEGA_KICK
	dw $0000 ; JUMP_KICK
	dw $0000 ; ROLLING_KICK
	dw $0000 ; SAND_ATTACK
	dw $0000 ; HEADBUTT
	dw $0000 ; HORN_ATTACK
	dw $0000 ; FURY_ATTACK
	dw $0140 ; HORN_DRILL
	dw $0000 ; TACKLE
	dw $0000 ; BODY_SLAM
	dw $0180 ; WRAP
	dw $0000 ; TAKE_DOWN
	dw $0100 ; THRASH
	dw $0000 ; DOUBLE_EDGE
	dw $0000 ; TAIL_WHIP
	dw $0000 ; POISON_STING
	dw $0000 ; TWINEEDLE
	dw $0000 ; PIN_MISSILE
	dw $0000 ; LEER
	dw $0000 ; BITE
	dw $0000 ; GROWL
	dw $4200 ; SUPER_TRANSFORM
	dw $0101 ; SING
	dw $0000 ; SUPERSONIC
	dw $1100 ; SONICBOOM
	dw $0000 ; DISABLE
	dw $0000 ; ACID
	dw $0000 ; EMBER
	dw $0000 ; FLAMETHROWER
	dw $0000 ; MIST
	dw $0000 ; WATER_GUN
	dw $0000 ; HYDRO_PUMP
	dw $0000 ; SURF
	dw $0000 ; ICE_BEAM
	dw $0000 ; BLIZZARD
	dw $0000 ; PSYBEAM
	dw $0000 ; BUBBLEBEAM
	dw $0000 ; AURORA_BEAM
	dw $0000 ; HYPER_BEAM
	dw $0000 ; PECK
	dw $0000 ; DRILL_PECK
	dw $0000 ; SUBMISSION
	dw $0000 ; LOW_KICK
	dw $0100 ; COUNTER
	dw $2100 ; SEISMIC_TOSS
	dw $0000 ; STRENGTH
	dw $0000 ; ABSORB
	dw $0000 ; MEGA_DRAIN
	dw $0000 ; LEECH_SEED
	dw $0102 ; GROWTH
	dw $0010 ; RAZOR_LEAF
	dw $0000 ; SOLARBEAM
	dw $0000 ; POISONPOWDER
	dw $0020 ; STUN_SPORE
	dw $0001 ; SLEEP_POWDER
	dw $0100 ; PETAL_DANCE
	dw $0000 ; STRING_SHOT
	dw $0900 ; DRAGON_RAGE
	dw $0180 ; FIRE_SPIN
	dw $0000 ; THUNDERSHOCK
	dw $0000 ; THUNDERBOLT
	dw $0020 ; THUNDER_WAVE
	dw $0000 ; THUNDER
	dw $0000 ; ROCK_THROW
	dw $0000 ; EARTHQUAKE
	dw $0140 ; FISSURE
	dw $0000 ; DIG
	dw $0000 ; TOXIC
	dw $0000 ; CONFUSION
	dw $0000 ; PSYCHIC_M
	dw $0001 ; HYPNOSIS
	dw $0000 ; MEDITATE
	dw $0102 ; AGILITY
	dw $0000 ; QUICK_ATTACK
	dw $0000 ; RAGE
	dw $0000 ; TELEPORT
	dw $2100 ; NIGHT_SHADE
	dw $0100 ; MIMIC
	dw $0000 ; SCREECH
	dw $0000 ; DOUBLE_TEAM
	dw $0104 ; RECOVER
	dw $0000 ; HARDEN
	dw $0000 ; MINIMIZE
	dw $0000 ; SMOKESCREEN
	dw $0100 ; CONFUSE_RAY
	dw $0000 ; WITHDRAW
	dw $0000 ; DEFENSE_CURL
	dw $0000 ; BARRIER
	dw $0000 ; LIGHT_SCREEN
	dw $0100 ; HAZE
	dw $0000 ; REFLECT
	dw $0102 ; FOCUS_ENERGY
	dw $0000 ; BIDE
	dw $0000 ; METRONOME
	dw $0100 ; MIRROR_MOVE
	dw $0008 ; SELFDESTRUCT
	dw $0000 ; EGG_BOMB
	dw $0000 ; LICK
	dw $0000 ; SMOG
	dw $0000 ; SLUDGE
	dw $0000 ; BONE_CLUB
	dw $0000 ; FIRE_BLAST
	dw $0000 ; WATERFALL
	dw $0180 ; CLAMP
	dw $0000 ; SWIFT
	dw $0000 ; SKULL_BASH
	dw $0000 ; SPIKE_CANNON
	dw $0000 ; CONSTRICT
	dw $0102 ; AMNESIA
	dw $0000 ; KINESIS
	dw $0104 ; SOFTBOILED
	dw $0000 ; HI_JUMP_KICK
	dw $0020 ; GLARE
	dw $0100 ; DREAM_EATER
	dw $0000 ; POISON_GAS
	dw $0000 ; BARRAGE
	dw $0000 ; LEECH_LIFE
	dw $0001 ; LOVELY_KISS
	dw $0000 ; SKY_ATTACK
	dw $0000 ; TRANSFORM
	dw $0000 ; BUBBLE
	dw $0000 ; DIZZY_PUNCH
	dw $0001 ; SPORE
	dw $0000 ; FLASH
	dw $0000 ; PSYWAVE
	dw $0000 ; SPLASH
	dw $0000 ; ACID_ARMOR
	dw $0010 ; CRABHAMMER
	dw $0008 ; EXPLOSION
	dw $0000 ; FURY_SWIPES
	dw $0000 ; BONEMERANG
	dw $0104 ; REST
	dw $0000 ; ROCK_SLIDE
	dw $0000 ; HYPER_FANG
	dw $0000 ; SHARPEN
	dw $0100 ; CONVERSION
	dw $0000 ; TRI_ATTACK
	dw $0100 ; SUPER_FANG
	dw $0010 ; SLASH
	dw $0100 ; SUBSTITUTE
	dw $4000 ; STRUGGLE
	assert_table_length NUM_ATTACKS + 1

; Selection weight per (difficulty row, move rank), as an ACCEPTANCE CHANCE OUT
; OF 64. The randomizer picks a candidate uniformly and then accepts it with
; this chance, retrying on rejection (see PartyGenWeightedPick). That is why the
; scale is out of 64 rather than a share of a total: rejection sampling is
; unbiased and needs only 8-bit maths, whereas summing weights over a ~70
; candidate pool would overflow a byte and force 16-bit accumulation plus a
; 16-bit modulo.
;
; Every row must contain at least one 64, or acceptance gets slow for a species
; whose whole candidate pool sits in a low-weight rank. A 0 makes that rank
; unreachable for that row.
;
; MOVE_RANK_OFFLIST is 0 in every row, which is belt and braces: the candidate
; filter already drops off-list moves before this table is consulted.
;
; The rows are provisional in the same sense as the ranks above - the shape
; Phase 5 tunes, not tuned values. They are deliberately NOT uniform, so a wrong
; row assignment shows up as a visible difficulty difference rather than as
; nothing at all.
MoveRankWeightTable::
	table_width NUM_MOVE_RANKS, MoveRankWeightTable
	;   F   D   C   B   A   S  off
	db 64, 48, 24,  8,  2,  1,  0 ; RANK_ROW_BAD
	db 48, 64, 40, 16,  6,  2,  0 ; RANK_ROW_EASY
	db 16, 32, 64, 48, 24, 10,  0 ; RANK_ROW_NORMAL
	db  6, 16, 40, 64, 56, 32,  0 ; RANK_ROW_HARD
	db  1,  4, 16, 40, 64, 64,  0 ; RANK_ROW_ELITE
	assert_table_length NUM_RANK_ROWS

; TM/HM move ids, indexed by wMonHLearnset bit position: bit i of that bitfield
; means "can learn TMMovesForPartyGen[i]" (the convention CanLearnTM establishes
; in engine/items/tms.asm, where the same counter indexes both).
;
; This is a SECOND emission of the same data as TechnicalMachines
; (data/moves/tmhm_moves.asm), which lives in bank $04. RogueBuildParty consults
; it once per TM candidate per rejection-sampling draw - hundreds of times per
; party - so a farcall per lookup was not viable, and 55 bytes in a bank with
; 12 KB free is the cheaper answer.
;
; It is NOT a maintenance hazard, because neither copy is hand-written: both are
; FOR loops over the same TM{02d:n}_MOVE constants from
; constants/item_constants.asm, which remains the single source of truth. Adding
; a TM there updates both. The ASSERT below fails the build if the two ever
; disagree in length.
TMMovesForPartyGen::
	table_width 1, TMMovesForPartyGen
FOR n, 1, NUM_TMS + 1
	db TM{02d:n}_MOVE
ENDR
FOR n, 1, NUM_HMS + 1
	db HM{02d:n}_MOVE
ENDR
	assert_table_length NUM_TM_HM
; Both this table and TechnicalMachines carry `assert_table_length NUM_TM_HM`,
; so a TM added to constants/item_constants.asm without regenerating one of them
; fails the build rather than desynchronising the two silently.
