#!/usr/bin/env python3
"""Emit the Facility full-room descriptor table from the validator's audit.

The descriptor table is 58 entries whose socket masks and item flags are
MEASURED, not authored, so transcribing them by hand is the one step in R4 where
a silent error would survive every build and most tests. This regenerates the
block instead.

Rows come from check_facility_premades.py directly, NOT from the audit artifact:
tools/pyboy_smoke/artifacts/ is gitignored, so depending on that file would mean
a fresh clone could not regenerate this table at all. The artifact stays a
human-readable dump of the same data.

Usage (from the repo root, inside WSL):
    python3 tools/gen_facility_room_table.py                      # prints asm

Splice the output over the block running from "PFacRoomDescriptors:" to the
"; generated by" marker in custom_functions/procedural_facility_gen.asm.
FacilityDescriptorTableFreshnessTest fails if you forget.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / "tools" / "pyboy_smoke" / "artifacts" / "facility_fullroom_audit.txt"

_VALIDATOR_SPEC = importlib.util.spec_from_file_location(
    "check_facility_premades", Path(__file__).resolve().parent / "check_facility_premades.py"
)
assert _VALIDATOR_SPEC and _VALIDATOR_SPEC.loader
validator = importlib.util.module_from_spec(_VALIDATOR_SPEC)
_VALIDATOR_SPEC.loader.exec_module(validator)


def audit_report() -> str:
    """The measured audit, computed fresh. The artifact file is only a dump."""
    return validator.format_report(validator.scan_fullrooms())

OK_LINE = re.compile(
    r"^(?P<file>\S+) W=(?P<w>\d+) H=(?P<h>\d+) sockets=(?P<sockets>[NESW]+) "
    r"item=(?P<item>\S+) exitsafe=(?P<exitsafe>[NWE]+|-) "
    r"spawnsafe=(?P<spawnsafe>[Y-]) status=OK$"
)

# C2: which map edges this payload may serve as the exit (boss) room on.
EXIT_FLAGS = {"N": "PFAC_TPL_EXIT_N", "W": "PFAC_TPL_EXIT_W", "E": "PFAC_TPL_EXIT_E"}

SOCKET_ORDER = "NESW"


def label_for(filename: str) -> str:
    stem = filename.rsplit(".", 1)[0].removeprefix("ProceduralFacility_")
    parts = [part for part in stem.split("_") if part]
    return "PFacTplData" + "".join(part[:1].upper() + part[1:] for part in parts)


MARK = "; generated by tools/gen_facility_room_table.py from "


def build_table() -> str:
    """The descriptor table block exactly as it belongs in the asm.

    Exposed separately from main() so test_facility_premades.py can assert the
    committed table still equals what the validator measures today. Socket
    masks, PFAC_TPL_ITEM, PFAC_TPL_EXIT_* and PFAC_TPL_SPAWN are all derived
    from the payload art, so a .blk edited without regenerating leaves the table
    describing art that no longer exists - and the build cannot notice.
    """
    text = _build()
    if text is None:
        raise SystemExit("audit produced no usable rows")
    return text


def main() -> int:
    text = _build()
    if text is None:
        return 1
    print(text)
    print(f"\n{MARK}tools/check_facility_premades.py")
    return 0


def _build() -> str | None:
    entries: list[tuple[int, int, str, bool, str, str]] = []
    for line in audit_report().splitlines():
        match = OK_LINE.match(line.strip())
        if not match:
            continue
        filename = match["file"]
        entries.append((
            int(match["w"]),
            int(match["h"]),
            "".join(c for c in SOCKET_ORDER if c in match["sockets"]),
            match["item"] != "-,-",
            filename,
            label_for(filename),
            "" if match["exitsafe"] == "-" else match["exitsafe"],
            match["spawnsafe"] == "Y",
        ))

    if not entries:
        print("audit contained no status=OK rows", file=sys.stderr)
        return None

    labels = [entry[5] for entry in entries]
    duplicates = {name for name in labels if labels.count(name) > 1}
    if duplicates:
        print(f"label collision: {sorted(duplicates)}", file=sys.stderr)
        return None

    groups: dict[tuple[int, int], list] = {}
    for entry in entries:
        groups.setdefault((entry[0], entry[1]), []).append(entry)
    for key, members in groups.items():
        if len(members) > 255:
            print(f"group {key} exceeds a byte count", file=sys.stderr)
            return None

    out: list[str] = []
    out.append("PFacRoomDescriptors:")
    for (w, h) in sorted(groups):
        members = groups[(w, h)]
        out.append("")
        out.append(f"PFacTpl{w}x{h}:")
        for _, _, sockets, item, filename, label, exit_safe, spawn in members:
            mask = " | ".join(f"PFAC_SOCKET_{c}" for c in sockets)
            bits = (["PFAC_TPL_ITEM"] if item else []) + [
                EXIT_FLAGS[c] for c in "NWE" if c in exit_safe
            ] + (["PFAC_TPL_SPAWN"] if spawn else [])
            flags = " | ".join(bits) if bits else "0"
            out.append(f"    db {w}, {h}, {mask}, {flags}")
            out.append(f"    dw {label}")
        out.append(f"PFacTpl{w}x{h}End:")
    out.append("")
    out.append("PFacRoomDescriptorsEnd:")
    out.append(
        "DEF PFAC_TPL_TOTAL EQU "
        "(PFacRoomDescriptorsEnd - PFacRoomDescriptors) / PFAC_TPL_STRIDE"
    )
    out.append(f"ASSERT PFAC_TPL_TOTAL == {len(entries)}")
    out.append("")
    out.append("; An empty size group is two zero bytes; a populated one names its run.")
    out.append("MACRO pfac_tpl_group ; \\1 = group label, \\2 = group end label")
    out.append("    db (\\1 - PFacRoomDescriptors) / PFAC_TPL_STRIDE")
    out.append("    db (\\2 - \\1) / PFAC_TPL_STRIDE")
    out.append("ENDM")
    out.append("MACRO pfac_tpl_no_group")
    out.append("    db 0, 0")
    out.append("ENDM")
    out.append("")
    out.append(
        "; Addressed by (footprint W - 3) * 7 + (footprint H - 3). "
        "Rows are W, columns H."
    )
    out.append("PFacRoomGroupTable:")
    for w in range(3, 10):
        out.append(f"    ; footprint width {w}")
        for h in range(3, 10):
            if (w, h) in groups:
                out.append(
                    f"    pfac_tpl_group PFacTpl{w}x{h}, PFacTpl{w}x{h}End"
                    f" ; {w}x{h}, {len(groups[(w, h)])}"
                )
            else:
                out.append(f"    pfac_tpl_no_group ; {w}x{h}")
    out.append(
        "ASSERT @ - PFacRoomGroupTable == "
        "PFAC_TPL_GROUP_COUNT * PFAC_TPL_GROUP_STRIDE"
    )
    out.append("")
    for (w, h) in sorted(groups):
        for _, _, _, _, filename, label, _, _ in groups[(w, h)]:
            out.append(f"{label}:")
            out.append(f'    INCBIN "maps/{filename}"')
            out.append(f"ASSERT @ - {label} == {w * h}")

    return "\n".join(out)


if __name__ == "__main__":
    raise SystemExit(main())
